name: Build DigitalWellbeingWPF

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.2.0

    - name: Restore NuGet packages
      run: nuget restore DigitalWellbeingWPF.sln

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3.1

    - name: Build solution
      run: msbuild DigitalWellbeingWPF.sln /p:Configuration=Release

    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: DigitalWellbeingEXE
        path: DigitalWellbeingWPF/bin/Release/
