name: Build DigitalWellbeingWPF

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore NuGet packages
      run: nuget restore DigitalWellbeingWPF.sln

    - name: Build solution
      run: msbuild DigitalWellbeingWPF.sln /p:Configuration=Release

    - name: Upload EXE
      uses: actions/upload-artifact@v3
      with:
        name: DigitalWellbeingEXE
        path: DigitalWellbeingWPF\bin\Release\
